# shmart native Zsh integration.
# This file is generated by `shmart shell install zsh` or `shmart init zsh`.

if [[ -n ${_SHMART_ZSH_LOADED:-} ]]; then
  return 0
fi
typeset -g _SHMART_ZSH_LOADED=1

: ${SHMART_BIN:=${commands[shmart]:-@SHMART_BIN@}}

if [[ ! -x "$SHMART_BIN" ]]; then
  print -u2 -- "shmart: executable not found; add it to PATH or set SHMART_BIN"
  unset _SHMART_ZSH_LOADED
  return 1
fi

# A source-build install may not be on PATH yet. Keep management commands usable
# without replacing a pre-existing command or function named `shmart`.
if (( ! $+commands[shmart] && ! $+functions[shmart] )); then
  shmart() {
    command "$SHMART_BIN" "$@"
  }
fi

typeset -g _SHMART_LAST_COMMAND=''
typeset -g _SHMART_PENDING_COMMAND=''
typeset -gi _SHMART_PENDING_STATUS=0

_shmart_preexec() {
  _SHMART_LAST_COMMAND=$1
}

_shmart_git_subcommand_is_unknown() {
  local command_line=$1
  local -a words
  words=(${(z)command_line}) 2>/dev/null || return 1
  [[ ${words[1]:-} == git && -n ${words[2]:-} ]] || return 1

  local subcommand=${words[2]}
  [[ $subcommand == -* ]] && return 1
  command git config --get "alias.$subcommand" >/dev/null 2>&1 && return 1

  local available
  available=$(command git help -a 2>/dev/null) || return 1
  local line
  local -a fields
  for line in ${(f)available}; do
    fields=(${=line})
    [[ ${fields[1]:-} == $subcommand ]] && return 1
  done
  return 0
}

_shmart_likely_usage_error() {
  local exit_status=$1 command_line=$2
  (( exit_status != 0 )) || return 1

  # Common shell/CLI usage statuses: cannot execute, command not found, misuse.
  (( exit_status == 126 || exit_status == 127 || exit_status == 2 )) && return 0

  # Zsh's NOMATCH error commonly returns 1 before a program starts.
  [[ $command_line == *\?* || $command_line == *\[* ]] && return 0

  # Git returns 1 for an unknown subcommand rather than the usual usage status.
  _shmart_git_subcommand_is_unknown "$command_line"
}

_shmart_precmd() {
  local exit_status=$?
  local command_line=$_SHMART_LAST_COMMAND
  _SHMART_LAST_COMMAND=''

  [[ -n $command_line ]] || return 0
  [[ $command_line == shmart(|' '*) ]] && return 0
  if _shmart_likely_usage_error "$exit_status" "$command_line"; then
    _SHMART_PENDING_COMMAND=$command_line
    _SHMART_PENDING_STATUS=$exit_status
  fi
}

_shmart_request() {
  local trigger=$1 command_line=$2 exit_status=${3:-}
  local choice_file
  local -a command_words argv_options
  command_words=(${(z)command_line}) 2>/dev/null || command_words=()
  local word
  for word in "${command_words[@]}"; do
    if [[ $word == <->'>'* || $word == <->'<'* ]]; then
      argv_options=()
      break
    fi
    case $word in
      '|'|'|&'|'||'|'&&'|';'|'&'|'('|')'|'{'|'}'|'<'|'>'|'>>'|'<<'|'<<<'|'<&'|'>&')
        argv_options=()
        break
        ;;
    esac
    argv_options+=(--argv "${(Q)word}")
  done
  choice_file=$(mktemp "${TMPDIR:-/tmp}/shmart-choice.XXXXXXXX") || {
    print -u2 -- 'shmart: could not create a temporary selection file'
    return 1
  }

  zle -I
  local tty_state=''
  if [[ -t 0 ]]; then
    tty_state=$(command stty -g 2>/dev/null)
    # ZLE uses raw input. The child menu needs canonical input, echo, and ISIG so
    # Enter, Ctrl-C, Ctrl-D, and Ctrl-Z retain their normal terminal behavior.
    command stty sane 2>/dev/null
  fi
  if [[ -n $exit_status ]]; then
    command "$SHMART_BIN" suggest \
      --trigger "$trigger" --command "$command_line" --status "$exit_status" \
      --output "$choice_file" "${argv_options[@]}" </dev/tty >/dev/tty
  else
    command "$SHMART_BIN" suggest \
      --trigger "$trigger" --command "$command_line" \
      --output "$choice_file" "${argv_options[@]}" </dev/tty >/dev/tty
  fi
  local result=$?
  if [[ -n $tty_state ]]; then
    command stty "$tty_state" 2>/dev/null
  fi

  local selection=''
  [[ -r $choice_file ]] && selection=$(<$choice_file)
  command rm -f -- "$choice_file"
  (( result == 0 )) || return $result
  REPLY=$selection
}

_shmart_is_management_command() {
  local command_line=$1
  local -a words
  words=(${(z)command_line}) 2>/dev/null || return 1
  [[ ${words[1]:-} == shmart ]] || return 1
  local -i index=2
  while (( index <= ${#words} )); do
    case ${words[index]} in
      --verbose)
        (( index++ ))
        ;;
      --config)
        (( index += 2 ))
        ;;
      --config=*)
        (( index++ ))
        ;;
      --)
        return 1
        ;;
      *)
        break
        ;;
    esac
  done
  case ${words[index]:-} in
    setup|doctor|config-path|shell|init|cli|help|-h|--help|-V|--version)
      return 0
      ;;
  esac
  return 1
}

_shmart_accept_line() {
  local command_line=$BUFFER
  if [[ $command_line != shmart && $command_line != shmart\ * ]]; then
    zle _shmart_original_accept_line
    return
  fi
  if _shmart_is_management_command "$command_line"; then
    zle _shmart_original_accept_line
    return
  fi

  local intent=${command_line#shmart}
  intent=${intent#"${intent%%[![:space:]]*}"}
  if [[ $intent == --(|' '*) ]]; then
    intent=${intent#--}
    intent=${intent#"${intent%%[![:space:]]*}"}
  fi
  if [[ -z $intent ]]; then
    zle -M 'usage: shmart <what you want the shell to do>'
    return
  fi

  REPLY=''
  _shmart_request explicit "$intent" || {
    BUFFER=''
    CURSOR=0
    zle reset-prompt
    return
  }
  [[ -n $REPLY ]] || {
    BUFFER=''
    zle reset-prompt
    return
  }
  BUFFER=$REPLY
  CURSOR=${#BUFFER}
  zle _shmart_original_accept_line
}

_shmart_line_init() {
  [[ -n $_SHMART_PENDING_COMMAND ]] || return 0
  [[ -z $BUFFER ]] || return 0

  local command_line=$_SHMART_PENDING_COMMAND
  local exit_status=$_SHMART_PENDING_STATUS
  _SHMART_PENDING_COMMAND=''
  _SHMART_PENDING_STATUS=0

  REPLY=''
  _shmart_request error "$command_line" "$exit_status" || {
    BUFFER=''
    CURSOR=0
    zle reset-prompt
    return
  }
  [[ -n $REPLY ]] || {
    zle reset-prompt
    return
  }
  BUFFER=$REPLY
  CURSOR=${#BUFFER}
  zle _shmart_original_accept_line
}

autoload -Uz add-zsh-hook add-zle-hook-widget
add-zsh-hook preexec _shmart_preexec
# Run first so another prompt hook cannot overwrite the previous exit status.
precmd_functions=(_shmart_precmd ${precmd_functions:#_shmart_precmd})
add-zle-hook-widget line-init _shmart_line_init

# Preserve whichever accept-line widget the user's Zsh setup currently provides.
zle -A accept-line _shmart_original_accept_line
zle -N _shmart_accept_line
zle -N accept-line _shmart_accept_line
