# shmart native Bash integration.
# This file is generated by `shmart shell install bash` or `shmart init bash`.

if [[ -n ${_SHMART_BASH_LOADED:-} ]]; then
  return 0
fi
_SHMART_BASH_LOADED=1

if [[ -z ${SHMART_BIN:-} ]]; then
  SHMART_BIN=$(type -P shmart 2>/dev/null || true)
fi
if [[ -z $SHMART_BIN ]]; then
  SHMART_BIN=@SHMART_BIN@
fi

if [[ ! -x "$SHMART_BIN" ]]; then
  printf 'shmart: executable not found; add it to PATH or set SHMART_BIN\n' >&2
  unset _SHMART_BASH_LOADED
  return 1
fi

_SHMART_BUSY=0
_SHMART_LAST_HISTORY_NUMBER=0
_SHMART_HISTORY_NUMBER_RESULT=0

_shmart_request() {
  local trigger=$1 command_line=$2 exit_status=$3
  shift 3
  local parse_command=0
  if [[ ${1:-} == --parse-command ]]; then
    parse_command=1
    shift
  fi

  local choice_file
  choice_file=$(mktemp "${TMPDIR:-/tmp}/shmart-choice.XXXXXXXX") || {
    printf 'shmart: could not create a temporary selection file\n' >&2
    return 1
  }

  local -a request
  request=(suggest --trigger "$trigger" --command "$command_line" --output "$choice_file")
  if [[ -n $exit_status ]]; then
    request+=(--status "$exit_status")
  fi
  if (( parse_command )); then
    request+=(--parse-command)
  fi
  local word
  for word in "$@"; do
    request+=(--argv "$word")
  done

  command "$SHMART_BIN" "${request[@]}"
  local result=$?
  local selection=
  if [[ -r $choice_file ]]; then
    IFS= read -r selection < "$choice_file"
  fi
  command rm -f -- "$choice_file"
  (( result == 0 )) || return "$result"
  REPLY=$selection
}

_shmart_is_management_args() {
  local -a words=("$@")
  local index=0
  while (( index < ${#words[@]} )); do
    case ${words[index]} in
      --verbose)
        (( index++ ))
        ;;
      --config)
        (( index += 2 ))
        ;;
      --config=*)
        (( index++ ))
        ;;
      --)
        return 1
        ;;
      *)
        break
        ;;
    esac
  done
  case ${words[index]:-} in
    setup|doctor|config-path|shell|init|cli|help|-h|--help|-V|--version)
      return 0
      ;;
  esac
  return 1
}

shmart() {
  if _shmart_is_management_args "$@"; then
    command "$SHMART_BIN" "$@"
    return $?
  fi

  if [[ ${1:-} == -- ]]; then
    shift
  fi
  if (( $# == 0 )); then
    printf 'usage: shmart <what you want the shell to do>\n' >&2
    return 2
  fi

  local intent=$*
  REPLY=
  _SHMART_BUSY=1
  _shmart_request explicit "$intent" "" "$@"
  local result=$?
  local selection=$REPLY
  _SHMART_BUSY=0
  (( result == 0 )) || return "$result"
  [[ -n $selection ]] || return 0
  builtin eval -- "$selection"
}

_shmart_git_subcommand_is_unknown() {
  local command_line=$1 subcommand
  if [[ $command_line =~ ^[[:space:]]*git[[:space:]]+([a-zA-Z0-9_-]+) ]]; then
    subcommand=${BASH_REMATCH[1]}
  else
    return 1
  fi
  [[ $subcommand == -* ]] && return 1
  command git config --get "alias.$subcommand" >/dev/null 2>&1 && return 1

  local available line
  available=$(command git help -a 2>/dev/null) || return 1
  while IFS= read -r line; do
    line=${line//$'\t'/ }
    case " $line " in
      *" $subcommand "*) return 1 ;;
    esac
  done <<< "$available"
  return 0
}

_shmart_likely_usage_error() {
  local exit_status=$1 command_line=$2
  (( exit_status != 0 )) || return 1
  (( exit_status == 126 || exit_status == 127 || exit_status == 2 )) && return 0
  _shmart_git_subcommand_is_unknown "$command_line"
}

_shmart_current_history_command() {
  local entry
  entry=$(HISTTIMEFORMAT= builtin history 1 2>/dev/null) || return 1
  if [[ $entry =~ ^[[:space:]]*([0-9]+)[[:space:]]+(.*)$ ]]; then
    _SHMART_HISTORY_NUMBER_RESULT=${BASH_REMATCH[1]}
    REPLY=${BASH_REMATCH[2]}
    return 0
  fi
  return 1
}

_shmart_precmd() {
  local exit_status=$1 final_status=$1
  (( _SHMART_BUSY == 0 )) || return "$exit_status"

  REPLY=
  _shmart_current_history_command || return "$exit_status"
  local history_number=$_SHMART_HISTORY_NUMBER_RESULT
  local command_line=$REPLY
  if (( history_number == _SHMART_LAST_HISTORY_NUMBER )); then
    return "$exit_status"
  fi
  _SHMART_LAST_HISTORY_NUMBER=$history_number
  [[ $command_line == shmart || $command_line == shmart\ * ]] && return "$exit_status"

  if _shmart_likely_usage_error "$exit_status" "$command_line"; then
    _SHMART_BUSY=1
    REPLY=
    _shmart_request error "$command_line" "$exit_status" --parse-command
    local request_status=$?
    local selection=$REPLY
    if (( request_status == 0 )) && [[ -n $selection ]]; then
      builtin eval -- "$selection"
      final_status=$?
    fi
    _SHMART_BUSY=0
  fi
  return "$final_status"
}

# Ignore the source/install command that loaded this integration.
if _shmart_current_history_command; then
  _SHMART_LAST_HISTORY_NUMBER=$_SHMART_HISTORY_NUMBER_RESULT
fi

_SHMART_PROMPT_DECLARATION=$(declare -p PROMPT_COMMAND 2>/dev/null || true)
case $_SHMART_PROMPT_DECLARATION in
  'declare -a'*|'declare -ax'*)
    _SHMART_PREVIOUS_PROMPT_COMMANDS=("${PROMPT_COMMAND[@]}")
    PROMPT_COMMAND=('_shmart_precmd "$?"' "${_SHMART_PREVIOUS_PROMPT_COMMANDS[@]}")
    ;;
  *)
    _SHMART_PREVIOUS_PROMPT_COMMAND=${PROMPT_COMMAND:-}
    PROMPT_COMMAND='_shmart_precmd "$?"'
    if [[ -n $_SHMART_PREVIOUS_PROMPT_COMMAND ]]; then
      PROMPT_COMMAND+='; '
      PROMPT_COMMAND+=$_SHMART_PREVIOUS_PROMPT_COMMAND
    fi
    ;;
esac
